apiVersion: core.openfeature.dev/v1alpha1
kind: FeatureFlagConfiguration
metadata:
  name: end-to-end
spec:
  featureFlagSpec: |
    {
      "booleanFlags": {
        "new-welcome-message": {
          "state": "enabled",
          "variants": {
            "enabled": true,
            "disabled": false
          },
          "defaultVariant": "enabled",
          "rules": []
        }
      }
    }
